DROP DATABASE IF EXISTS `timetofood`;
CREATE DATABASE `timetofood`;
USE `timetofood`;

DROP TABLE IF EXISTS `Favorites`;
DROP TABLE IF EXISTS `ReservationsDishes`;
DROP TABLE IF EXISTS `Reservations`;
DROP TABLE IF EXISTS `Dishes`;
DROP TABLE IF EXISTS `Tables`;
DROP TABLE IF EXISTS `Providers`;
DROP TABLE IF EXISTS `Clients`;

CREATE TABLE IF NOT EXISTS `Clients`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`phone` INT UNSIGNED NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`credit` INT UNSIGNED DEFAULT 0,
	`levelpoints` INT NOT NULL DEFAULT 0,
	`url` VARCHAR(255) NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE KEY(username),
	UNIQUE KEY(email),
	UNIQUE KEY(phone)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Providers`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`restaurant` VARCHAR(50) NOT NULL,
	`phone` INT UNSIGNED NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`credit` INT UNSIGNED DEFAULT 0,
	`levelpoints` INT NOT NULL DEFAULT 0,
	`url` VARCHAR(255) NULL,
	`description` TEXT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE KEY(username),
	UNIQUE KEY(email),
	UNIQUE KEY(restaurant),
	UNIQUE KEY(phone)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Tables`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`provider_id` INT UNSIGNED NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`description` TEXT NOT NULL,
	`chairs` INT UNSIGNED NOT NULL DEFAULT 0,
	`available` ENUM('0', '1') NOT NULL DEFAULT '1',
	`url` VARCHAR(255) NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE KEY(name),
	FOREIGN KEY(provider_id)
		REFERENCES Providers(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Dishes`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`provider_id` INT UNSIGNED NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`description` TEXT NOT NULL,
	`price` INT UNSIGNED NOT NULL DEFAULT 0,
	`available` ENUM('0', '1') NOT NULL DEFAULT '1',
	`url` VARCHAR(255) NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE KEY(name),
	UNIQUE KEY(url),
	FOREIGN KEY(provider_id)
		REFERENCES Providers(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Reservations`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`client_id` INT UNSIGNED NOT NULL,
	`table_id` INT UNSIGNED NOT NULL,
	`meeting` TIMESTAMP NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	FOREIGN KEY(client_id)
		REFERENCES Clients(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(table_id)
		REFERENCES Tables(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `ReservationsDishes`(
	`id` INT UNSIGNED NOT NULL,
	`reservation_id` INT UNSIGNED NOT NULL,
	`dish_id` INT UNSIGNED NOT NULL,
	`amount` INT UNSIGNED NOT NULL,
	`total` INT UNSIGNED NOT NULL,
	FOREIGN KEY(reservation_id)
		REFERENCES Reservations(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(dish_id)
		REFERENCES Dishes(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Favorites`(
	`client_id` INT UNSIGNED NOT NULL,
	`restaurant_id` INT UNSIGNED NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(client_id)
		REFERENCES Clients(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(restaurant_id)
		REFERENCES Providers(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;


INSERT INTO Clients (username, email, phone, password)
	VALUES ('Hilario', 'hmaldonado0@ucol.mx', '1231231231', '4297f44b13955235245b2497399d7a93');
INSERT INTO Providers (username, email, restaurant, phone, password)
	VALUES ('Hilario', 'hmaldonado0@ucol.mx', 'El vaquero', '1231231231', '4297f44b13955235245b2497399d7a93');

/*
CREATE TABLE IF NOT EXISTS `Regions`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE KEY(name)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Cities`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`region_name` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`type` VARCHAR(10) NOT NULL,
	`latitude` DECIMAL(5, 2) NOT NULL,
	`longitude` DECIMAL(5, 2) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE KEY(name),
	FOREIGN KEY(region_name)
		REFERENCES Regions(name)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Users`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`admin` ENUM('0', '1') NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE KEY(username),
	UNIQUE KEY(email)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Tags`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`url` VARCHAR(255) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE KEY(url)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Products`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT UNSIGNED NOT NULL,
	`tag_id` INT UNSIGNED NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`description` TEXT NOT NULL,
	`price` INT UNSIGNED NOT NULL,
	`amount` INT UNSIGNED NOT NULL,
	`status` ENUM('0', '1') NOT NULL DEFAULT '0',
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	UNIQUE KEY(name),
	FOREIGN KEY(user_id)
		REFERENCES Users(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(tag_id)
		REFERENCES Tags(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `ProductsFiles`(
	`url` VARCHAR(255) NOT NULL,
	`product_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY(url),
	FOREIGN KEY(product_id)
		REFERENCES Products(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `Orders`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`region_id` INT UNSIGNED NOT NULL,
	`city_id` INT UNSIGNED NOT NULL,
	`user_id` INT UNSIGNED NOT NULL,
	`total` INT UNSIGNED NOT NULL,
	`direction` VARCHAR(255) NOT NULL,
	`postalcode` VARCHAR(4) NOT NULL,
	`description` TEXT NOT NULL,
	`delivery` VARCHAR(10) NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	FOREIGN KEY(region_id)
		REFERENCES Regions(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(city_id)
		REFERENCES Cities(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `OrdersItems`(
	`order_id` INT UNSIGNED NOT NULL,
	`product_id` INT UNSIGNED NOT NULL,
	`amount` INT UNSIGNED NOT NULL,
	FOREIGN KEY(order_id)
		REFERENCES Orders(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(product_id)
		REFERENCES Products(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;
*/